front/package-lock.json
front/package.json
front/src/components/StockChart.jsx
front/src/routes/login/Login.jsx

-[V] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
dev/fe/stockChart -> dev
stockChart 컴포넌트 추가

주식 차트 컴포넌트 추가

---

front/package-lock.json
front/package.json
front/postcss.config.js
front/src/App.jsx
front/src/index.css
front/tailwind.config.js

-[✔️] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
dev/fe/farm -> develop
테일윈드 css를 사용하기 위한 초기 세팅 추가
정상적으로 테일윈드 css가 적용되는 것을 확인할 수 있습니다.

feat: tailwind 세팅 추가

---

front/package-lock.json
front/src/components/Landing3D.jsx
front/src/routers/auth-router.jsx
front/src/routes/landingPage/Landing.jsx
front/src/routes/login/Login.jsx

-[V] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
dev/fe/langing3d -> dev
- 3D 모델 크기 증가
- 마우스 event 민감도 조정
- 3D 모델 canvas 위치 및 색상 변경
- 랜딩페이지 추가

랜딩페이지 추가 및 3D 모델 조정

---

front/src/components/Profile.jsx

dev/fe/miniProfile -> develop
현재 사용자 턴과 다음 턴 버튼을 추가 했습니다.
이전과 마찬가지로 데이터와 CSS가 없는 관계로 생략했습니다.

사용자 턴 안내 및 다음 턴 버튼 추가

---

front/package-lock.json
front/package.json
front/src/components/StockCard.jsx
front/src/routes/main/Market.jsx
front/tailwind.config.js

ex) dev/feat/market/stockcard -> dev/feat/market/layout
- 주식 카드 기본 틀 생성
- 주식 카드 누르면 select 되도록 기본 설정만 해둠(추후 db랑 변수명 통일할 수 있도록 바꿔줘야함)

feat: 주식 카드 추가

---

front/src/components/StockButton.jsx
front/src/components/StockDetail.jsx
front/src/routes/main/Market.jsx
front/tailwind.config.js

ex) dev/fe/market/button -> dev/fe/market/layout
- 매도, 매수 버튼 추가
- 주식 디테일에서 선택한 주식 이름 볼 수 있도록함
- 주식 디테일 뼈대 잡음

[FEAT] 매도, 매수 버튼 추가

---

server/app.js
server/config/db.connect.js
server/routes/api/users.js

dev/be/profile -> dev
user 정보 가져오기 및 mysql pool 설정 변경되었습니다.

[FEAT] mysql 설정 변경 및 user 정보 가져오기 테스트(닉네임 불러오기)

---

server/routes/api/quiz.js

dev/be/feat/quiz-answer -> develop
퀴즈 채점 결과를 반영하고 맞았을 경우 포인트를 추가로 지급합니다.
<포스트맨 실행 결과>
<DB 값 변동>
Before ->
hold_stock
quiz
After ->
hold_stock
quiz
close #19

[FEAT] 퀴즈 채점 확인 및 포인트 부여

---

front/src/routes/login/Login.jsx
front/src/routes/signup/Signup.jsx
server/app.js
server/package-lock.json
server/package.json
server/routes/api/users.js
server/utils/auth.js

dev/be/feat/login -> develop
회원가입, 로그인 기능을 추가하고
프론트부분과 연동까지 마쳤습니다.
1. POSTMAN에서 http://localhost:3000/api/users/signup에 nickname과 password를 적고 post요청을 보내면 아래 사진과 같이 성공적인 응답이 오는 것을 확인 할 수 있습니다.
데이터 베이스에서도 성공적으로 추가가 되었고
2. http://localhost:3000/api/users/signin에 방금 가입한 닉네임과 비밀번호를 기입하여 post요청을 보내면 성공적으로 응답이 오고
authToken도 잘 보이는 것을 확인할 수 있습니다.
3. 프론트 로그인과 회원가입 페이지에서 api연동을 하여 성공적으로 회원가입, 로그인이 되는 것을 확인 할 수 있습니다.

[FEAT] 회원가입 로그인 로직 추가 및 연동

---

server/routes/api/market.js

ex) dev/be/market -> develop
시장 매도 api를 구현했습니다.
시장 랭킹 불러오기 api 날짜를 수정했습니다.
시장 매도 api를 구현중에 있습니다.

[WIP] [FEAT] 마켓관련 API 작성 중

---

server/routes/api/market.js

ex) dev/be/market -> develop
매도 API 구현 완료했습니다.

[FEAT] 마켓 API 구현중 

---

server/routes/api/users.js

dev/be/farm -> develop
get 요청시 cookie에서 authToken을 가져와 decode하고 유저의 아이디를 추출하는 라우터를 추가하였습니다. 
잘 받아 오는 것을 확인 할 수 있습니다.

[FEAT] 유저의 아이디를 추출하는 라우터 추가

---

server/routes/api/index.js
server/routes/api/ranking.js

ex) dev/be/ranking -> develop
수익률 계산하여 수익률 관련 모든 테이블 UPDATE했습니다.

[FEAT] 랭킹 수익률 API 구현 완료

---

server/routes/api/market.js

ex) dev/be/market -> develop
턴증가시 변경사항들을 업데이트하게 구현했습니다.

[FEAT] 시장 API 모두 구현 완료

---

server/routes/api/farm.js
server/routes/api/users.js

dev/be/farm -> develop
1. 회원가입시 이미지 번호를 1~4에서 랜덤으로 뽑아서 삽입하고 hold_stock 테이블에 기본정보를 삽입하도록 추가 하였습니다.
2. 라우터에서 유저 아이디를 가져오는 코드를 추가하였습니다.

[FEAT] 이미지 랜덤으로 1부터 4까지 추가

---

server/routes/api/farm.js
server/routes/api/users.js

dev/be/farm -> develop
유저의 정보를 불러오는 라우터를 수정하였습니다.
로그인 한 유저의 id값을 잘 추출하여 정보를 불러오는 것을 확인 할 수 있습니다.

[FIX] 유저 정보 불러오는 라우터 수정

---

front/package-lock.json
front/package.json
front/src/components/Stock/OrderModal.jsx
front/src/components/StockDetail.jsx
front/src/components/Toast.jsx

ex) dev/fe/feat/alert -> develop
- sweetalert 라이브러리 설치
- 주식 사고 팔 때 alert창 보여주기

[FEAT] Sweetalert 라이브러리 추가

---

.github/workflows/main.yml
server/app.js
server/middleware/verifyUser.js
server/routes/api/index.js
server/routes/api/market.js

ex) dev/be/market -> develop
로그인 전 랜딩페이지, 로그인페이지 외에 접근 불가 코드 추가
로그인 후 시장에서 로그인된 user로 사용하게 변경

[UPDATE] 시장 로그인 된 userId로 사용하게 변경

---

front/package-lock.json
front/package.json
front/src/components/CompanyProfile.jsx
front/src/routes/login/Login.jsx
front/src/routes/signup/Signup.jsx

dev/fe/farm -> develop
1. 회원가입, 로그인 페이지에서 엔터키가 작동되게 기능 추가 하였습니다.
2. 회원가입시 공백 처리 및 비밀번호 3자리 이상을 필수로 작성하는 기능을 추가였습니다.
1. 직접 해보면 엔터키가 제대로 작동되는 것을 확인 할 수 있습니다.
2. 회원가입 페이지에서 닉네임을 공백으로 설정하거나 비밀번호를 2자리 이하로 작성하는 경우 경고문이 뜨면서 회원가입이 되지 않는 기능입니다. 아래는 테스트 결과입니다.

[FEAT] 회원가입시 공백 처리, 비밀번호 3자리 이상 기능 추가 및 회원가입 로그인시 엔터키 작동기능 추가

---

server/config/db.connect.js
server/routes/api/users.js

dev/be/profile -> develop
DB스키마 수정으로 인한 user 정보 불러오기 API 오류를 수정하였습니다.
- 수익률 불러오기 오류 해결
- 잔고가 아닌 재산 총액을 불러오는 현상 해결
-

[FIX] user 정보 불러오기 오류 수정

---

front/src/components/NewsModal.jsx
front/src/components/Profile.jsx
front/src/components/StockDetail.jsx
front/src/routes/main/Market.jsx
front/tailwind.config.js

ex) dev/fe/feat/market/news -> develop
- 뉴스 모달 추가
- 다음턴으로 넘겼을 때 뉴스가 존재하면 뉴스 보여주기
- 뉴스에 애니메이션 추가
- 주식 수량 불러오는 API 응답값 변경에 따른 로직 변경

[FEAT] 뉴스 모달 추가

---

front/package-lock.json
front/package.json
front/src/App.jsx
front/src/store/store.jsx

ex) dev/fe/feat/reduxpersist -> develop
- 새로고침 시 redux persist를 사용하여 유저 정보 저장

[FEAT] redux-persist 사용하여 유저 정보 저장

---

.github/workflows/main.yml

develop -> main
주말에 주식장이 열리지 않아 api 호출 시 서버 app crash 나던 현상을 수정

[FIX] 주말 시 주식 장 api 요청 안하게 수정

---

front/src/components/BgmBtn.jsx
front/src/components/Navbar.jsx
front/src/routes/login/Login.jsx
front/src/routes/signup/Signup.jsx

dev/fe/login  -> develop
1. 로그인 페이지와 회원가입 페이지 요소 위치를 수정하였습니다.
2. 로그인 페이지에 회원가입 버튼을 추가하였습니다.
3. 로그인과 회원가입에서 뜨는 alert창도 라이브러리를 적용하였습니다.
4. navbar에 있는 bgm버튼 디자인을 수정하였습니다.
1. 로그인 페이지와 회원가입 페이지 요소 위치를 수정하고 회원가입 버튼을 추가하였습니다.
2.  이미 존재하는 닉네임, 로그인에 실패하였습니다 등등 로그인과 회원가입에 관련된 에러메세지에 alert라이브러리를 적용하였습니다.
3. navbar에 있는 bgm버튼 디자인을 수정하였습니다.

[FEAT] 로그인 페이지와 회원가입 페이지 요소 수정, alert 라이브러리 적용, bgm 버튼 디자인 수정

---

server/routes/api/quiz.js
server/utils/schedule.js

dev/be/feat/openAPI -> develop
DB 퀴즈 정답 테이블에 어제/오늘 시세와 종목 이름을 추가적으로 저장하고,
퀴즈 정답 확인 API 응답에도 해당 내용을 추가했습니다.

[UPDATE] 퀴즈 정답 확인 API 응답 수정

---

server/routes/api/market.js

ex) dev/be/fix/market/rank -> develop
- 날짜 계산 로직들 변경했습니다

[FIX] 날짜 계산 로직 수정

---

server/routes/api/market.js

ex) dev/be/fix/market -> develop
- 주식 정보 불러올 때 회사 설명도 불러오도록 수정

[UPDATE] 회사 정보도 불러오도록 수정

---

server/app.js
server/package-lock.json
server/package.json
server/routes/api/quiz.js
server/utils/schedule.js

dev/be/feat/holiday -> develop
공공데이터포털 특일 정보 API 연동을 통해 매 달 1일마다 DB에 해당 월의 공휴일 정보(근로자의 날, 한 해 마지막 평일 추가)를 저장합니다.
날짜를 받아 공휴일인지 아닌지 반환하는 API를 구현했습니다.

[FEAT] 퀴즈 - 공휴일 확인 기능 구현

---

server/utils/schedule.js

dev/be/feat/openAPI -> develop
서버 로그 확인용 console.log 코드 추가

[UPDATE] 서버 로그 확인용 console.log 코드 추가

---

server/routes/api/market.js

ex) dev/be/fix/market -> develop
- 다음턴 넘길 때의 날짜 계산 수정
- 랭킹 쿼리에서 요청한 유저의 정보만 찾도록 수정

[FIX] 날짜 계산 수정 및 랭킹 업데이트 쿼리문 수정

---

front/src/components/CompanyProfile.jsx

dev/fe/company -> develop
회사 프로필에 있는 문구를 좀 더 쉽게 변경하였습니다.

[UPDATE] 회사 프로필 문구 변경

---

front/src/components/CompanyProfile.jsx

dev/fe/companyProfile -> develop
원 -> 프디로 문구 변경하였습니다.

[UPDATE] 원 -> 프디로 문구 변경

---

server/routes/api/history.js
server/routes/api/index.js
server/routes/api/market.js

dev/be/feat/history -> develop
전체/종목별/거래종류별 거래내역을 반환하는 기능을 구현하였습니다.
전체조회 - 데이터 없음
전체조회 - 데이터 있음
거래종류별 조회  - 데이터 없음
거래종류별 조회  - 데이터 있음
종목별 조회 - 데이터 없음
종목별 조회 - 데이터 있음
종목, 거래내역 선택 조회 - 데이터 없음
종목, 거래내역 선택 조회 - 데이터 있음

[FEAT] 거래내역 조회 API 구현

---

server/utils/schedule.js

dev/be/feat/openAPI -> develop
신한투자증권 투자전략 API 요청 함수가 실행되는 시각을 변경하였습니다.

[UPDATE] 투자전략 API 요청 실행 시간 변경

---

front/src/components/Profile.jsx
front/src/components/Ranking/RankComponent.jsx
front/src/store/userSlice.jsx

ex) dev/fe/extra -> develop
- undefined 일 때는 0으로 주도록 해보았습니다

[FIX] tofixed 에러 수정

---

front/package-lock.json
front/package.json
front/src/components/QuizModal.jsx
front/tailwind.config.js
front/vite.config.js

ex) dev/fe/extra -> develop
- 뉴스 더보기 디자인 변경
- 스크롤바 라이브러리 추가

[UPDATE] 뉴스 더보기 디자인 수정

---

front/src/components/Navbar.jsx
front/src/routes/main/Quiz.jsx

develop -> main
onclick 버튼 추가했습니다.

[UPDATE] 이미지에 onclick 추가
